jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
      
      - name: Check Dependencies
        run: deno run --allow-read scripts/check_imports.ts
      
      - name: Lint
        run: deno lint 